# Generated by Django 5.1.2 on 2025-05-14 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='auto_audio_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='material',
            name='translation_en',
            field=models.TextField(blank=True, verbose_name='英文翻译'),
        ),
        migrations.AddField(
            model_name='material',
            name='translation_ja',
            field=models.TextField(blank=True, verbose_name='日文翻译'),
        ),
        migrations.AddField(
            model_name='material',
            name='translation_zh',
            field=models.TextField(blank=True, verbose_name='中文翻译'),
        ),
        migrations.AlterField(
            model_name='material',
            name='question_text',
            field=models.TextField(verbose_name='听力文本'),
        ),
    ]
