# Generated by Django 5.1.2 on 2025-05-14 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_material_auto_audio_generated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='language',
            field=models.CharField(choices=[('ja', '日语'), ('en', '英语'), ('zh-CN', '中文')], default='ja', max_length=10, verbose_name='朗读语言'),
        ),
    ]
