# Generated by Django 5.1.2 on 2025-05-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_material_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerrecord',
            name='ease',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='answerrecord',
            name='interval',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answerrecord',
            name='next_review',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answerrecord',
            name='repetitions',
            field=models.IntegerField(default=0),
        ),
    ]
